### ISSUE TITLE
Sandbox does not appear to work with sample code in documentation

### ISSUE THREAD

**Issue by karmajunkie** [salemove/ex_freddy#25]
When running the sample code provided by `Freddy.Adapters.Sandbox` in its documentation, I get the following error output:

```
iex(3)> alias Freddy.Connection
Freddy.Connection
iex(4)> alias Freddy.Core.Exchange
Freddy.Core.Exchange
iex(5)> {:ok, conn} = Connection.start_link(adapter: :sandbox)
{:ok, #PID<0.276.0>}
iex(6)> {:ok, channel} = Connection.open_channel(conn)
{:ok,
 %Freddy.Core.Channel{adapter: Freddy.Adapter.Sandbox, chan: #PID<0.279.0>}}
iex(7)> :ok = Exchange.declare(%Exchange{name: "test"}, channel)
:ok
iex(8)> Freddy.Adapter.Sandbox.history(conn)

17:31:25.634 [error] GenServer #PID<0.276.0> terminating
** (FunctionClauseError) no function clause matching in Freddy.Connection.handle_call/3
    (freddy) lib/freddy/connection.ex:223: Freddy.Connection.handle_call({:history, :all, false}, {#PID<0.244.0>, #Reference<0.16082119.1428946948.206517>}, {:state, Freddy.Adapter.Sandbox, [[]], #PID<0.278.0>, %{#Reference<0.16082119.1428946948.206461> => {:value, %Freddy.Core.Channel{adapter: Freddy.Adapter.Sandbox, chan: #PID<0.279.0>}, [#Reference<0.16082119.1428946948.206464>, #PID<0.279.0>]}, #Reference<0.16082119.1428946948.206464> => {:assoc, #Reference<0.16082119.1428946948.206461>}, #PID<0.279.0> => {:assoc, #Reference<0.16082119.1428946948.206461>}}, {:backoff, {:backoff, 1000, 10000, 1000, :jitter, :undefined, :undefined}}})
    (connection) lib/connection.ex:488: Connection.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.244.0>): {:history, :all, false}
** (EXIT from #PID<0.244.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Freddy.Connection.handle_call/3
        (freddy) lib/freddy/connection.ex:223: Freddy.Connection.handle_call({:history, :all, false}, {#PID<0.244.0>, #Reference<0.16082119.1428946948.206517>}, {:state, Freddy.Adapter.Sandbox, [[]], #PID<0.278.0>, %{#Reference<0.16082119.1428946948.206461> => {:value, %Freddy.Core.Channel{adapter: Freddy.Adapter.Sandbox, chan: #PID<0.279.0>}, [#Reference<0.16082119.1428946948.206464>, #PID<0.279.0>]}, #Reference<0.16082119.1428946948.206464> => {:assoc, #Reference<0.16082119.1428946948.206461>}, #PID<0.279.0> => {:assoc, #Reference<0.16082119.1428946948.206461>}}, {:backoff, {:backoff, 1000, 10000, 1000, :jitter, :undefined, :undefined}}})
        (connection) lib/connection.ex:488: Connection.handle_call/3
        (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

Erlang version: 21.0.6
Elixir version: 1.7.2

I've tried against both master and v0.14.0 with similar results.

**Comment by take-five** [comment]
Thanks for reporting the bug. Example in documentation is most likely incorrect and I'll change it next week. In the meantime you can check code from https://github.com/salemove/ex_freddy/blob/master/test/support/connection_case.ex#L23 to get an idea on how to use the Sandbox adapter history.
